# Generated by Django 3.2.5 on 2021-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210815_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_facebook',
            new_name='social_website',
        ),
    ]
